---

- name: install cloud-init
  yum:
    name: "{{ item }}"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ cloud_init_packages }}"

- name: config cloud-init
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ cloud_init_files }}"

- name: config /etc/fstab
  lineinfile: 
    dest: "{{ fstab_file }}"
    regexp: 'UUID=(.*)\s+/'
    line: 'UUID=\1   /   ext4    defaults     0 1'
    backrefs: yes

- name: config network scripts
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ interfaces_file }}"

- name: config /etc/rc.local
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items: "{{ rc_local_file }}"
 
- name: remove udev network rules and i386 arch packages
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ removed_files }}"

- name: config /etc/ssh/sshd_config
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ sshd_file }}"

- name: config /etc/sysconfig/network
  lineinfile: 
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
  with_items: "{{ no_zero_config }}"

- name: remove zeroconf route in ifup-eth
  shell: sed -i '/Add Zeroconf route/,+4d' /etc/sysconfig/network-scripts/ifup-eth
  ignore_errors: True

- name: config time zone Asia/Ho_Chi_Minh
  file: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{ timezone_config }}"

- name: config /etc/default/grub
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ grub_config }}"
  notify:
    - update grub

- name: config SELinux
  lineinfile: 
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
  with_items: "{{ selinux_config }}"

- name: remove packages
  yum: 
    name: "{{ item }}"
    state: absent
  with_items: "{{ removed_packages }}"
  ignore_errors: True

- name: config /etc/yum.conf
  copy: 
    src: yum.conf
    dest: /etc/yum.conf
    owner: root
    group: root
    mode: 0644

- name: Enable IPv6
  copy:
    src: network
    dest: /etc/sysconfig/network
    owner: root
    group: root
    mode: 644
  when: ipv6_enabled == True
