---
- name: config file sshd_config
  copy: 
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644

- name: disable network config
  copy: 
    src: "99-disable-network-config.cfg"
    dest: "/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg"
    owner: root
    group: root
    mode: 0644

- name: Clean net-config
  copy: 
    src: "01-netcfg.yaml"
    dest: "/etc/netplan/01-netcfg.yaml"
    owner: root
    group: root
    mode: 0644

- name: config /etc/netplan/50-cloud-init.yml
  template:
    src: "50-cloud-init.yaml"
    dest: "/etc/netplan/50-cloud-init.yaml"
    owner: root
    group: root
    mode: 0644

- name: remove udev network rules and i386 arch packages
  file: 
    path: "{{ item }}" 
    state: absent
  with_items: "{{ removed_files }}"

- name: config /etc/fstab
  copy: 
    src: "fstab"
    dest: "/etc/fstab"
    owner: root
    group: root
    mode: 0644

- name: set label for root-disk
  command: "e2label /dev/vda1 cloudimg-rootfs"

- name: config /etc/default/grub
  copy: 
    src: "grub"
    dest: "/etc/default/grub"
    owner: root
    group: root
    mode: 0644
  notify:
    - update grub

- name: set timezone Asia/Ho_Chi_Minh
  copy: 
    content: "Asia/Ho_Chi_Minh"
    dest: "/etc/timezone"
    owner: root
    group: root
    mode: 0644
  notify:
    - update timezone

- name: config /etc/rc.local
  template: 
    src: "rc.local"
    dest: "/etc/rc.local"
    owner: root
    group: root
    mode: 0755

- name: Set timeout dhcp v6
  copy:
    src: dhclient.conf
    dest: /etc/dhcp/dhclient.conf
  when: ipv6_enabled == True
